version: '3.9'
services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_list
    ports:
      - '5432:5432'
    volumes: 
      - ./database/postgres-data:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_list -h 127.0.0.1"]
      interval: 5s
      timeout: 100s
      retries: 20

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_list
      - POSTGRES_PORT=5432
    container_name: backend
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    
volumes:
  db:
    driver: local
    